kind: Deployment
metadata:
  name: brain-tasks-deployment
  labels:
    app: brain-tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
        - name: brain-tasks-container
          image: 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
          ports:
            - containerPort: 3000
          imagePullPolicy: Always


